name: Build Mac App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install dependencies
      run: npm install
    
    - name: Build Electron App
      run: npm run build-mac
    
    - name: Upload DMG
      uses: actions/upload-artifact@v4
      with:
        name: Blueprint-Mac
        path: dist/*.dmg
