name: Build App
on: push
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Create Mac App
      run: |
        mkdir -p Blueprint.app/Contents/MacOS
        mkdir -p Blueprint.app/Contents/Resources
        cp Terminal.html Blueprint.app/Contents/Resources/
        cp -r *.html *.js *.py Blueprint.app/Contents/Resources/
        echo '#!/bin/bash' > Blueprint.app/Contents/MacOS/Blueprint
        echo 'cd "$(dirname "$0")/../Resources"' >> Blueprint.app/Contents/MacOS/Blueprint
        echo 'python3 server.py &' >> Blueprint.app/Contents/MacOS/Blueprint
        echo 'sleep 2' >> Blueprint.app/Contents/MacOS/Blueprint
        echo 'open http://localhost:9767/Terminal.html' >> Blueprint.app/Contents/MacOS/Blueprint
        chmod +x Blueprint.app/Contents/MacOS/Blueprint
        zip -r Blueprint-Mac.zip Blueprint.app
    - uses: actions/upload-artifact@v4
      with:
        name: Blueprint-Mac
        path: Blueprint-Mac.zip
